// <auto-generated />
namespace Chicken.Web.DataContexts.InventoryMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ACat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ACat));
        
        string IMigrationMetadata.Id
        {
            get { return "201904251800567_ACat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
