// <auto-generated />
namespace Chicken.Web.DataContexts.BookMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Chick_Wing : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Chick_Wing));
        
        string IMigrationMetadata.Id
        {
            get { return "201903192126301_Chick_Wing"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
